### ISSUE TITLE
Crash from Currents on temper build -b js

### ISSUE THREAD

**Issue by ShawSumma** [temperlang/temper#118]
Not sure if this is related to anything else... but:

```
java.util.concurrent.RejectedExecutionException: Task lang.temper.common.currents.CurrentsKt$makeSelfSafeEventDispatcher$1$$Lambda$56/0x00007fafe0109a98@7384285 rejected from java.util.concurrent.ThreadPoolExecutor@5c3bee4a[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2330]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2065)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:833)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1365)
        at lang.temper.common.currents.CurrentsKt$makeSelfSafeEventDispatcher$1.invoke(Currents.kt:600)
        at lang.temper.common.currents.CurrentsKt$makeSelfSafeEventDispatcher$1.invoke(Currents.kt:598)
        at lang.temper.common.currents.CurrentStateMachine.setStateIfTo(CurrentStateMachine.kt:147)
        at lang.temper.common.currents.Currents.checkDone(Currents.kt:303)
        at lang.temper.common.currents.Currents.futureDone(Currents.kt:220)
        at lang.temper.common.currents.Currents.access$futureDone(Currents.kt:23)
        at lang.temper.common.currents.Currents$watch$3.invoke(Currents.kt:208)
        at lang.temper.common.currents.Currents$watch$3.invoke(Currents.kt:207)
        at lang.temper.common.currents.Currents.watch$lambda$8(Currents.kt:207)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:914)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
```

On Debian WSL `temper build -b js`

**Comment by ShawSumma** [comment]
This happens once in a blue moon for me. Not too sure what causes it.

**Comment by tjpalmer** [comment]
We had an old parallel build system that was unreliable, and we've built a new one that's unreliable. Maybe there's just one little thing wrong somewhere, but I don't know how to find such holes. Not sure if starting from scratch again is smart either.

We still haven't replaced all kotlin coroutines, which presumably doesn't automatically fix things, anyway. They're used still in some file system handling. Also in langserver, which presumably doesn't matter above.

I'm just rather 😭 about things this regard, though.

**Comment by tjpalmer** [comment]
I did find and fix a problem recently with langserver and removing folders from the workspace. So I sometimes can find holes, but the random things are so much harder.
