### ISSUE TITLE
Name conflicts for `scripts`?

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#134]
Seems weird things can happen with packages in Python named `scripts`:

```py
> Task :cli:test

BuildTest > mypycBackend() FAILED


Poetry could not find a pyproject.toml file in /home/tom/projects/temper/cli or its parents
Traceback (most recent call last):
  File "/home/tom/apps/py39/bin/test", line 8, in <module>
    sys.exit(test())
  File "/home/tom/projects/tld/scripts.py", line 14, in test
    test_only()
  File "/home/tom/projects/tld/scripts.py", line 18, in test_only
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'site'
Currents Done, no pending work

> Task :cli:test
```

Why we call into that `test` thing, I don't know. But in addition to the `tld/scripts.py` conflict above, @mikesamuel has also mentioned hitting this with the `scripts` package in the main Temper repo.

This presumably has an effect only on internal Temper dev at the moment, but it would be good to work out these wrinkles.

**Comment by tjpalmer** [comment]
Actually, might be only a `tld` thing rather than a main `temper(-prepublic)` thing. Here's from tld's pyproject.toml:

```toml
[tool.poetry.scripts]
build = "scripts:build"
serve = "scripts:serve"
test = "scripts:test"
test-only = "scripts:test_only"
```

**Comment by tjpalmer** [comment]
Yep, they totally [get installed in the poetry virtual env](https://python-poetry.org/docs/pyproject/#scripts) at least, and apparently I've managed to install them in my main env at some point.

**Comment by tjpalmer** [comment]
And running `poetry install` keeps putting `tld-support` back in my main env instead of a project-specific one, every time I `pip uninstall` it.

**Comment by tjpalmer** [comment]
And for what it's worth:

```
$ poetry config --list | grep virtualenvs
virtualenvs.create = true
```

**Comment by tjpalmer** [comment]
This might be my issue, [from the docs](https://python-poetry.org/docs/configuration/#virtualenvscreate):

```
If Poetry detects it’s running within an activated virtual environment, it will never create a new virtual environment, regardless of the value set for virtualenvs.create.
```

**Comment by tjpalmer** [comment]
I replaced my wsl python with a non-venv setup, and the poetry install bother went away. Probably should still change the `test` script name.
