### ISSUE TITLE
Broken java & py naming in larger projects

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#161]
For [temper-regex-parser](https://github.com/temperlang/temper-regex-parser) current main, some backends work:

```
temper-regex-parser> temper test -b csharp -b js -b lua
Tests passed: 66 of 66
```

But java doesn't:

```java
temper-regex-parser> temper test -b java
## exception.class: lang.temper.be.cli.CommandFailed
## exception.msg: C:\Users\work2\Apps\apache-maven-3.8.6\bin\mvn.cmd failed: exit code = 1
## exception.trace: lang.temper.be.cli.CommandFailed: C:\Users\work2\Apps\apache-maven-3.8.6\bin\mvn.cmd failed: exit code = 1
        at lang.temper.be.cli.Effort.asResult(Command.kt:147)
...
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/work2/Documents/projects/temper-regex-parser/temper.out/java/temper-regex-parser/src/main/java/temper/regex_parser/Parser.java:[17,1] cannot find symbol
  symbol:   static End__102
  location: class temper.regex_parser.RegexParserGlobal
[ERROR] /C:/Users/work2/Documents/projects/temper-regex-parser/temper.out/java/temper-regex-parser/src/main/java/temper/regex_parser/Parser.java:[18,1] cannot find symbol
  symbol:   static Dot__101
  location: class temper.regex_parser.RegexParserGlobal
[ERROR] /C:/Users/work2/Documents/projects/temper-regex-parser/temper.out/java/temper-regex-parser/src/main/java/temper/regex_parser/Parser.java:[19,1] cannot find symbol
  symbol:   static Word__106
  location: class temper.regex_parser.RegexParserGlobal
...
Tests passed: 0 of 22 (22 not run)
Test failed
```

And neither does py:

```py
temper-regex-parser> temper test -b py
Test failed (py): capture - Traceback (most recent call last):
  File "C:\Users\work2\Documents\projects\temper-regex-parser\temper.out\py\temper-regex-parser\tests\test_tests.py", line 17, in test___capture__125
    regex_53 = compile_48('(?cent=\\d)(?tens=\\d)(?ones=\\d)')
...
  File "C:\Users\work2\Documents\projects\temper-regex-parser\temper.out\py\temper-regex-parser\temper_regex_parser\__init__.py", line 342, in read_seq
    if isinstance26(regex_177, CodePoints_25):
NameError: name 'CodePoints_25' is not defined
...
Tests passed: 4 of 22
Test failed
```

**Comment by tjpalmer** [comment]
One main issue for both be-java & be-py is that the same export can get different local names in different modules. For example:

```kt
names.nameLookup_field.nameMap_field.entries.filter { it.key.displayName == "Dot" }
result = {ArrayList@8641}  size = 2
 {SourceName@7685} Dot__101 -> {Info@7686} Info(decl=Module(-work///).Import(Dot__101), fqName=null, use=[Module(-work///).TypeDeclaration(Parser__44).NormalMethod(readSingle__161).Reference(Dot__101)])
 {SourceName@8424} Dot__41 -> {Info@11842} Info(decl=Module(-work//tests/).Import(Dot__41), fqName=null, use=[Module(-work//tests/).Test(structure__159).Reference(Dot__41)])
```

But these backends don't account for that. For example, here's Dot from the import map in be-java:

```kt
names.nameLookup_field.imports_field.entries.filter { it.key.displayName == "Dot" }
result = {ArrayList@12423}  size = 1
 {ExportedName@8423} nym`std//regex.temper.md`.Dot -> {SourceName@8424} Dot__41
```

And the inverse mapping is built from that in be-java:

```kt
names.nameLookup_field.inverseImports_field.entries.filter { it.key.displayName == "Dot" }
result = {ArrayList@11863}  size = 1
 {SourceName@8424} Dot__41 -> {ExportedName@8423} nym`std//regex.temper.md`.Dot
```

Upshot is that it can't find `Dot__101` and defaults to thinking it comes from a different place. Similar issues exist in be-py, but it tends to be more around constructor calls and a different issue around type annotations.
