### ISSUE TITLE
Python version check can fail for test on watch

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#42]
On [branch watch-test](https://github.com/temperlang/temper-prepublic/compare/watch-test), I tried this:

```
> temper watch -t py -t js
```

But I got this, and it continued on each edit of a file being watched, where this exception comes from trying to remove the stderr file of the python version check:

```kt
java.nio.file.FileSystemException: C:\Users\work2\Documents\projects\rosettacodes\temper.out\version-stderr: The process cannot access the file because it is being used by another process
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:275)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at lang.temper.be.cli.LocalCliEnv.remove(LocalCliEnv.kt:169)
        at lang.temper.be.cli.CliEnv.remove$default(CliEnv.kt:109)
        at lang.temper.be.cli.Specifics$validate$1$1$1.invoke(Specifics.kt:42)
        at lang.temper.be.cli.Specifics$validate$1$1$1.invoke(Specifics.kt:40)
        at lang.temper.common.RResult.flatMap(RResult.kt:63)
        at lang.temper.be.cli.Specifics$validate$1$1.invoke(Specifics.kt:40)
        at lang.temper.be.cli.Specifics$validate$1$1.invoke(Specifics.kt:34)
        at lang.temper.common.RResult.flatMap(RResult.kt:63)
        at lang.temper.be.cli.Specifics$validate$1.invoke(Specifics.kt:34)
        at lang.temper.be.cli.Specifics$validate$1.invoke(Specifics.kt:33)
        at lang.temper.common.RResult.flatMap(RResult.kt:63)
        at lang.temper.be.cli.Specifics$DefaultImpls.validate(Specifics.kt:33)
        at lang.temper.be.py.helper.PythonSpecifics.validate(PythonSpecifics.kt:23)
        at lang.temper.be.cli.CliEnv.validate(CliEnv.kt:58)
        at lang.temper.cli.WatchTesting$buildListener$1.translated(WatchTesting.kt:58)
        at lang.temper.cli.DoWatchKt$doWatch$watcher$1.translated(DoWatch.kt:57)
        at lang.temper.tooling.Watcher$internalBuildListener$1.translated(Watcher.kt:70)
        at lang.temper.compile.BuildEventProcessor$translatedHandler$1.handle(BuildEventProcessor.kt:86)
        at lang.temper.compile.eventing.EventBus$HandleTask.run(EventBus.kt:325)
        at lang.temper.tooling.ExceptionDumpingExecutorService.execute$lambda$0(ExceptionDumpingExecutorService.kt:17)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

Tests passed: 5 of 5
```

However, I also typically get this:

```
> temper test -b py -b js
Tests passed: 10 of 10
```

I'm not sure what the difference is.

And this also typically works:

```
> temper watch -t py
Tests passed: 5 of 5
Built in 4.50s: rosetta-code-examples std (java js py lua)
```

**Comment by tjpalmer** [comment]
> [@tjpalmer](https://github.com/tjpalmer) Maybe close or update this as it's before our build changes?

I have no idea if it's still an issue. I also haven't done as much writing code in Temper recently and so haven't used temper watch often enough to know if it's likely to come up or not.

Have you seen this happen to you? If not, we could close it for now and just reopen it or open a new one if we see the issue again.
