### ISSUE TITLE
Translate to missing function crashes repl and maybe build

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#52]
Seems similar to #48.

```ts
$ hi()
1: hi()
   ┗┛
[interactive#0:1+0-2]@G: Expected function type, but got Invalid
1: hi()
   ┗┛
[interactive#0:1+0-2]@G: No declaration for hi
interactive#0: fail
$ translate(0, "js")
Exception in thread "main" java.lang.NullPointerException: null cannot be cast to non-null type T of lang.temper.cli.repl.Repl.<no name provided>.get
        at lang.temper.cli.repl.Repl$sharedLocationContext$1.get(Repl.kt:116)
        at lang.temper.format.ConsoleBackedContextualLogSink.log(ConsoleBackedContextualLogSink.kt:61)
        at lang.temper.log.LogSink$DefaultImpls.log$default(LogSink.kt:17)
        at lang.temper.be.Backend.<init>(Backend.kt:118)
        at lang.temper.be.js.JsBackend.<init>(JsBackend.kt:103)
        at lang.temper.be.js.JsBackend.<init>(JsBackend.kt)
        at lang.temper.be.js.JsBackend$Companion.make(JsBackend.kt:565)
        at lang.temper.be.js.JsBackend$Companion.make(JsBackend.kt:511)
        at lang.temper.cli.repl.ReplTranslateFn.makeBackendForTranslation$lambda$8$makeBackend(ReplTranslateFn.kt:225)
        at lang.temper.cli.repl.ReplTranslateFn.makeBackendForTranslation(ReplTranslateFn.kt:233)
        at lang.temper.cli.repl.ReplTranslateFn.invoke(ReplTranslateFn.kt:102)
        at lang.temper.interp.Interpreter.dispatchCall(Interpreter.kt:629)
        at lang.temper.interp.Interpreter.interpretCall(Interpreter.kt:788)
        at lang.temper.interp.Interpreter.interpretTreeNotSpammy(Interpreter.kt:242)
        at lang.temper.interp.Interpreter.interpretTree(Interpreter.kt:224)
        at lang.temper.interp.Interpreter.interpretTree$default(Interpreter.kt:209)
        at lang.temper.interp.Interpreter.interpretEdge$interp(Interpreter.kt:176)
        at lang.temper.interp.Interpreter.interpretFlowElement(Interpreter.kt:503)
        at lang.temper.interp.Interpreter.interpretBlock(Interpreter.kt:436)
        at lang.temper.interp.Interpreter.interpretBlock$default(Interpreter.kt:306)
        at lang.temper.interp.Interpreter.interpretTreeNotSpammy(Interpreter.kt:241)
        at lang.temper.interp.Interpreter.interpretTree(Interpreter.kt:224)
        at lang.temper.interp.Interpreter.interpretReuseEnvironment(Interpreter.kt:164)
        at lang.temper.frontend.runtime.RuntimeEmulationStage.process(RuntimeEmulationStage.kt:49)
        at lang.temper.frontend.Module$advance$1.invoke(Module.kt:538)
        at lang.temper.frontend.Module$advance$1.invoke(Module.kt:397)
        at lang.temper.frontend.TopLevelBindings.whileSynchronized(TopLevelBindings.kt:93)
        at lang.temper.frontend.Module.advance(Module.kt:397)
        at lang.temper.cli.repl.Repl.processLine(Repl.kt:312)
...
```

This crash from `temper build` might also be related:

```ts
[-work//form.temper.md+356-372]: Cannot translate validateMinValue not available from implicits: ❎
kotlin.NotImplementedError: An operation is not implemented: non-function types?
        at lang.temper.be.java.JavaTranslator$ModuleScope.callFunctionValue(JavaTranslator.kt:1449)
        at lang.temper.be.java.JavaTranslator$ModuleScope.callExpr(JavaTranslator.kt:1254)
        at lang.temper.be.java.JavaTranslator$ModuleScope.expr(JavaTranslator.kt:1149)
        at lang.temper.be.java.JavaTranslator$ModuleScope.assignment(JavaTranslator.kt:1114)
        at lang.temper.be.java.JavaTranslator$ModuleScope.stmt(JavaTranslator.kt:991)
        at lang.temper.be.java.JavaTranslator$ModuleScope.block(JavaTranslator.kt:987)
        at lang.temper.be.java.JavaTranslator$ModuleScope.stmt(JavaTranslator.kt:992)
        at lang.temper.be.java.JavaTranslator$ModuleScope.tryStmt(JavaTranslator.kt:1096)
        at lang.temper.be.java.JavaTranslator$ModuleScope.stmt(JavaTranslator.kt:1020)
        at lang.temper.be.java.JavaTranslator$ModuleScope.block(JavaTranslator.kt:987)
        at lang.temper.be.java.JavaTranslator$ModuleScope.stmt(JavaTranslator.kt:992)
        at lang.temper.be.java.JavaTranslator$ModuleScope.ifStmt(JavaTranslator.kt:1078)
        at lang.temper.be.java.JavaTranslator$ModuleScope.elseBlock(JavaTranslator.kt:1084)
        at lang.temper.be.java.JavaTranslator$ModuleScope.ifStmt(JavaTranslator.kt:1079)
        at lang.temper.be.java.JavaTranslator$ModuleScope.stmt(JavaTranslator.kt:1000)
        at lang.temper.be.java.JavaTranslator$ModuleScope.block(JavaTranslator.kt:987)
        at lang.temper.be.java.JavaTranslator$ModuleScope.stmt(JavaTranslator.kt:992)
        at lang.temper.be.java.JavaTranslator$ModuleScope.stmt(JavaTranslator.kt:1004)
        at lang.temper.be.java.JavaTranslator$ModuleScope.block(JavaTranslator.kt:987)
        at lang.temper.be.java.JavaTranslator$ModuleScope.classDeclare(JavaTranslator.kt:741)
        at lang.temper.be.java.JavaTranslator$ModuleScope.module(JavaTranslator.kt:213)
        at lang.temper.be.java.JavaTranslator.translate(JavaTranslator.kt:155)
        at lang.temper.be.java.JavaBackend.translate(JavaBackend.kt:129)
        at lang.temper.compile.handlers.TranslationManager.doTranslate(TranslationManager.kt:521)
...
```

**Comment by tjpalmer** [comment]
The repl case looks good to me, and the `temper build` report is vague and easily unrelated.

```ts
$ hi()
1: hi()
   ┗┛
[interactive#0:1+0-2]@G: No declaration for hi
interactive#0: fail
$ translate(0, "js")
1: hi()
   ┗┛
[interactive#0:1+0-2]: hi has not been declared
Not generating code for interactive#0
Translated js for interactive#0
  interactive/
interactive#1: void
```

So I'll close this issue.
