### ISSUE TITLE
repl: trying to translate failing chunk raises NPE

### ISSUE THREAD

**Issue by mikesamuel** [temperlang/temper#61]
```
$ temper repl
$ let f(): Void { console.log("Hello, World!") }
interactive#0: void
$ translate(7, "java")
1: translate(7, "java")
             ⇧
[interactive#1:1+10-11]@R: Expected value of type Int in 0..1 | String like "interactive#0" not 7
interactive#1: fail
$ translate(1, "java")
1: translate(7, "java")
             ⇧
[interactive#1:1+10-11]: Expected value of type Int in 0..1 | String like "interactive#0" not 7
Exception in thread "main" java.lang.NullPointerException: null cannot be cast to non-null type T of lang.temper.cli.repl.Repl.<no name provided>.get
	at lang.temper.cli.repl.Repl$sharedLocationContext$1.get(Repl.kt:116)
	at lang.temper.format.ConsoleBackedContextualLogSink.log(ConsoleBackedContextualLogSink.kt:61)
	at lang.temper.log.LogSink$DefaultImpls.log$default(LogSink.kt:17)
	at lang.temper.be.Backend.<init>(Backend.kt:118)
	at lang.temper.be.java.JavaBackend.<init>(JavaBackend.kt:106)
	at lang.temper.be.java.JavaBackend.<init>(JavaBackend.kt)
	at lang.temper.be.java.JavaBackend$JavaFactory.make(JavaBackend.kt:342)
	at lang.temper.be.java.JavaBackend$JavaFactory.make(JavaBackend.kt:290)
	at lang.temper.cli.repl.ReplTranslateFn.makeBackendForTranslation$lambda$8$makeBackend(ReplTranslateFn.kt:225)
```

**Comment by tjpalmer** [comment]
Forgot this was written up already. While working #77, I got this fixed in my current branch. Maybe will be posting a pr today.
