### ISSUE TITLE
`temper repl -b js` troubles on Windows

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#69]
After a somewhat lengthy delay, I got this when I tried `temper repl -b js` on my Windows machine:

```kt
PS C:\Users\work2\Documents\projects\tutorial\hello> temper repl -b js
## exception.class: lang.temper.be.cli.CommandFailed
## exception.msg: C:\Users\work2\Apps\node-v18.14.1-win-x64\npm.cmd failed: exit code = -4082
## exception.trace: lang.temper.be.cli.CommandFailed: C:\Users\work2\Apps\node-v18.14.1-win-x64\npm.cmd failed: exit code = -4082
        at lang.temper.be.cli.Effort.asResult(Command.kt:147)
        at lang.temper.be.cli.LocalCliEnv$LocalCliTool$run$3.invoke(LocalCliEnv.kt:299)
        at lang.temper.be.cli.LocalCliEnv$LocalCliTool$run$3.invoke(LocalCliEnv.kt:298)
        at lang.temper.common.RResultKt.flatMap(RResult.kt:231)
        at lang.temper.be.cli.LocalCliEnv$LocalCliTool.run(LocalCliEnv.kt:298)
        at lang.temper.be.cli.CliTool.run(CliTool.kt:29)
        at lang.temper.be.cli.CliTool.run$default(CliTool.kt:23)
        at lang.temper.be.js.RunJsKt.runJsBestEffort(RunJs.kt:187)
        at lang.temper.be.js.NodeSpecifics.runBestEffort(NodeSpecifics.kt:42)
        at lang.temper.cli.Runner$runOnBackend$1$1.invoke(Runner.kt:323)
        at lang.temper.cli.Runner$runOnBackend$1$1.invoke(Runner.kt:322)
        at lang.temper.cli.Runner.usingCliEnv(Runner.kt:309)
        at lang.temper.cli.Runner.runOnBackend(Runner.kt:322)
        at lang.temper.cli.Runner.runRequest(Runner.kt:291)
        at lang.temper.cli.Runner.runBackendsForModuleSync(Runner.kt:216)
        at lang.temper.cli.Runner.doRunWithLogs(Runner.kt:161)
        at lang.temper.cli.Runner.doRun(Runner.kt:75)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5$executeBackendRepl$ok$1.invoke(Cli.kt:431)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5$executeBackendRepl$ok$1.invoke(Cli.kt:417)
        at lang.temper.cli.Main.wrapBuild(Cli.kt:655)
        at lang.temper.cli.Main.access$wrapBuild(Cli.kt:68)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5.executeBackendRepl(Cli.kt:417)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5.execute(Cli.kt:359)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
        at lang.temper.cli.Main.run(Cli.kt:642)
        at lang.temper.cli.Cli.main(Cli.kt:741)

## exception.cause.null: true
## Command: cd C:\Users\work2\Documents\projects\tutorial\temper.out\js; C:\Users\work2\Apps\node-v18.14.1-win-x64\npm.cmd install
## Stdout: npm ERR! code EBUSY
npm ERR! syscall symlink
npm ERR! path C:\Users\work2\Documents\projects\tutorial\temper.out\js\hello
npm ERR! dest C:\Users\work2\Documents\projects\tutorial\temper.out\js\node_modules\hello
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, symlink 'C:\Users\work2\Documents\projects\tutorial\temper.out\js\hello' -> 'C:\Users\work2\Documents\projects\tutorial\temper.out\js\node_modules\hello'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\work2\AppData\Local\npm-cache\_logs\2024-01-16T02_21_51_081Z-debug-0.log

## Steps to access the test: The environment is in predefined directory:
cd 'C:\Users\work2\Documents\projects\tutorial\temper.out'
## Command that was run: cd C:\Users\work2\Documents\projects\tutorial\temper.out\js
C:\Users\work2\Apps\node-v18.14.1-win-x64\npm.cmd "install"
## Individual step: installing the node libraries
## exception.class: lang.temper.be.cli.CommandFailed
## exception.msg: C:\Users\work2\Apps\node-v18.14.1-win-x64\npm.cmd failed: exit code = -4082
## exception.trace: lang.temper.be.cli.CommandFailed: C:\Users\work2\Apps\node-v18.14.1-win-x64\npm.cmd failed: exit code = -4082
        at lang.temper.be.cli.Effort.asResult(Command.kt:147)
        at lang.temper.be.cli.LocalCliEnv$LocalCliTool$run$3.invoke(LocalCliEnv.kt:299)
        at lang.temper.be.cli.LocalCliEnv$LocalCliTool$run$3.invoke(LocalCliEnv.kt:298)
        at lang.temper.common.RResultKt.flatMap(RResult.kt:231)
        at lang.temper.be.cli.LocalCliEnv$LocalCliTool.run(LocalCliEnv.kt:298)
        at lang.temper.be.cli.CliTool.run(CliTool.kt:29)
        at lang.temper.be.cli.CliTool.run$default(CliTool.kt:23)
        at lang.temper.be.js.RunJsKt.runJsBestEffort(RunJs.kt:187)
        at lang.temper.be.js.NodeSpecifics.runBestEffort(NodeSpecifics.kt:42)
        at lang.temper.cli.Runner$runOnBackend$1$1.invoke(Runner.kt:323)
        at lang.temper.cli.Runner$runOnBackend$1$1.invoke(Runner.kt:322)
        at lang.temper.cli.Runner.usingCliEnv(Runner.kt:309)
        at lang.temper.cli.Runner.runOnBackend(Runner.kt:322)
        at lang.temper.cli.Runner.runRequest(Runner.kt:291)
        at lang.temper.cli.Runner.runBackendsForModuleSync(Runner.kt:216)
        at lang.temper.cli.Runner.doRunWithLogs(Runner.kt:161)
        at lang.temper.cli.Runner.doRun(Runner.kt:75)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5$executeBackendRepl$ok$1.invoke(Cli.kt:431)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5$executeBackendRepl$ok$1.invoke(Cli.kt:417)
        at lang.temper.cli.Main.wrapBuild(Cli.kt:655)
        at lang.temper.cli.Main.access$wrapBuild(Cli.kt:68)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5.executeBackendRepl(Cli.kt:417)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5.execute(Cli.kt:359)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
        at lang.temper.cli.Main.run(Cli.kt:642)
        at lang.temper.cli.Cli.main(Cli.kt:741)

## exception.cause.null: true
## Command: cd C:\Users\work2\Documents\projects\tutorial\temper.out\js; C:\Users\work2\Apps\node-v18.14.1-win-x64\npm.cmd install
## Stdout: npm ERR! code EBUSY
npm ERR! syscall symlink
npm ERR! path C:\Users\work2\Documents\projects\tutorial\temper.out\js\hello
npm ERR! dest C:\Users\work2\Documents\projects\tutorial\temper.out\js\node_modules\hello
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, symlink 'C:\Users\work2\Documents\projects\tutorial\temper.out\js\hello' -> 'C:\Users\work2\Documents\projects\tutorial\temper.out\js\node_modules\hello'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\work2\AppData\Local\npm-cache\_logs\2024-01-16T02_21_51_081Z-debug-0.log

## Steps to access the test: The environment is in predefined directory:
cd 'C:\Users\work2\Documents\projects\tutorial\temper.out'
## Command that was run: cd C:\Users\work2\Documents\projects\tutorial\temper.out\js
C:\Users\work2\Apps\node-v18.14.1-win-x64\npm.cmd "install"
## Individual step: installing the node libraries
npm ERR! code EBUSY
npm ERR! syscall symlink
npm ERR! path C:\Users\work2\Documents\projects\tutorial\temper.out\js\hello
npm ERR! dest C:\Users\work2\Documents\projects\tutorial\temper.out\js\node_modules\hello
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, symlink 'C:\Users\work2\Documents\projects\tutorial\temper.out\js\hello' -> 'C:\Users\work2\Documents\projects\tutorial\temper.out\js\node_modules\hello'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\work2\AppData\Local\npm-cache\_logs\2024-01-16T02_21_51_081Z-debug-0.log

Repl failed
```

On a second attempt, I got things like this:

```kt
PS C:\Users\work2\Documents\projects\tutorial\hello> temper repl -b js
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'c':
The specified module could not be found.

The specified module could not be found.

The specified module could not be found.

Native library (win32-x86-64/c.dll) not found in resource path (... lots of jars ...)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:307)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:467)
        at com.sun.jna.Library$Handler.<init>(Library.java:192)
        at com.sun.jna.Native.loadLibrary(Native.java:672)
        at com.sun.jna.Native.loadLibrary(Native.java:656)
        at com.sun.akuma.CLibrary.<clinit>(CLibrary.java:89)
        at lang.temper.be.cli.LocalCliEnv$LocalCliTool.runAsLast(LocalCliEnv.kt:305)
        at lang.temper.be.js.RunJsKt.runInteractiveReplAndHalt(RunJs.kt:316)
        at lang.temper.be.js.RunJsKt.runJsBestEffort(RunJs.kt:214)
        at lang.temper.be.js.NodeSpecifics.runBestEffort(NodeSpecifics.kt:42)
        at lang.temper.cli.Runner$runOnBackend$1$1.invoke(Runner.kt:323)
        at lang.temper.cli.Runner$runOnBackend$1$1.invoke(Runner.kt:322)
        at lang.temper.cli.Runner.usingCliEnv(Runner.kt:309)
        at lang.temper.cli.Runner.runOnBackend(Runner.kt:322)
        at lang.temper.cli.Runner.runRequest(Runner.kt:291)
        at lang.temper.cli.Runner.runBackendsForModuleSync(Runner.kt:216)
        at lang.temper.cli.Runner.doRunWithLogs(Runner.kt:161)
        at lang.temper.cli.Runner.doRun(Runner.kt:75)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5$executeBackendRepl$ok$1.invoke(Cli.kt:431)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5$executeBackendRepl$ok$1.invoke(Cli.kt:417)
        at lang.temper.cli.Main.wrapBuild(Cli.kt:655)
        at lang.temper.cli.Main.access$wrapBuild(Cli.kt:68)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5.executeBackendRepl(Cli.kt:417)
        at lang.temper.cli.Main$run$makeArgParser$subcommands$5.execute(Cli.kt:359)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
        at lang.temper.cli.Main.run(Cli.kt:642)
        at lang.temper.cli.Cli.main(Cli.kt:741)
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:197)
                ... 27 more
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:210)
                ... 27 more
        Suppressed: java.lang.UnsatisfiedLinkError: The specified module could not be found.

                at com.sun.jna.Native.open(Native Method)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:270)
                ... 27 more
        Suppressed: java.io.IOException: Native library (win32-x86-64/c.dll) not found in resource path (... lots of jars ...)
                at com.sun.jna.Native.extractFromResourcePath(Native.java:1145)
                at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:281)
                ... 27 more
```

At the moment, on repeated attempts, I'm getting the latter rather than the former problem. It's not a huge delay in this case. I also tried rerunning gradlew installDist without a change in behavior.

**Comment by tjpalmer** [comment]
Seems I fixed this already:

```js
temper-regex-engine> temper repl -b js
Running C:\Users\work2\Apps\node-v18.14.1-win-x64\node.exe v18.14.1
REPL is running with these Temper libraries pre-loaded:
╔═══════════════════╦═════════════════╗
║Library Name       ║JS identifier    ║
╠═══════════════════╬═════════════════╣
║temper-regex-engine║temperRegexEngine║
╠═══════════════════╬═════════════════╣
║temper-regex-parser║temperRegexParser║
╚═══════════════════╩═════════════════╝
Type ".help" for more information.
> temperRegexParser.parse("a.*b")
Sequence {}
```
