### ISSUE TITLE
Poor garbage handling in backends and repl

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#77]
I'm calling a missing function. In addition to frontend errors, I get stack traces from be-csharp and be-java. Here's the start of them:

```kt
51: e(i: Int): String { padLeft(i.toString(16), 2,
                        ┗━━━━━┛51:
[-work/src//helpers.temper.md+1047-1054]: Cannot translate padLeft not available from implicits: ❎
e(i: Int): String { padLeft(i.toString(16), 2,
kotlin.NotImplementedError: An operation is not implemented.
        at lang.temper.be.csharp.CSharpTranslator.translateExpression(CSharpTranslator.kt:940)
...
[-work/src//helpers.temper.md+1047-1054]: Cannot translate padLeft not available from implicits: ❎
kotlin.NotImplementedError: An operation is not implemented: non-function types?
        at lang.temper.be.java.JavaTranslator$ModuleScope.callFunctionValue(JavaTranslator.kt:1384)
```

Other backends don't show stack traces.

But similar things also crash the repl but for any backend I've tried so far, so presumably a different issue, but it might be nice to tackle both at once. Here's an example:

```kt
$ hi(5)
1: hi(5)
   ┗┛
[interactive#0:1+0-2]@G: Expected function type, but got Invalid
1: hi(5)
   ┗┛
[interactive#0:1+0-2]@G: No declaration for hi
interactive#0: fail
$ translate(0, "js")
Exception in thread "main" java.lang.NullPointerException: null cannot be cast to non-null type T of lang.temper.cli.repl.Repl.<no name provided>.get
        at lang.temper.cli.repl.Repl$sharedLocationContext$1.get(Repl.kt:113)
        at lang.temper.format.ConsoleBackedContextualLogSink.log(ConsoleBackedContextualLogSink.kt:61)
        at lang.temper.log.LogSink$DefaultImpls.log$default(LogSink.kt:17)
        at lang.temper.be.Backend.<init>(Backend.kt:122)
        at lang.temper.be.js.JsBackend.<init>(JsBackend.kt:106)
...
```

**Comment by tjpalmer** [comment]
Also getting this stack trace in be-csharp:

```kt
58: if (needed <= 0) {
59:   return string;
60: }
    ⇧
[-work/src//helpers.temper.md+1303-1352]@G: Expected subtype of String, but got Void
kotlin.NotImplementedError: An operation is not implemented.
        at lang.temper.be.csharp.CSharpTranslator.translateValueReference(CSharpTranslator.kt:1881)
```

The full (broken/unfinished) function where that comes from:

```ts
    let padLeft(string: String, minSize: Int, pad: String): String {
      let needed = minSize - string.codePoints.length;
      if (needed <= 0) {
        return string;
      }
    }
```

**Comment by tjpalmer** [comment]
Another case. I wrote code that looks like this:

```ts
    export oklabToLinearSrgb(lab: Lab): Rgb {
      //
    }
```

That's missing `let`. In addition to frontend errors, which are ok, it causes lots of stack traces across at least c#, java, & lua:

```kt
b: Lab): Rgb {
kotlin.NotImplementedError: An operation is not implemented.
        at lang.temper.be.csharp.CSharpTranslator.translateExpression(CSharpTranslator.kt:940)
...
33: export oklabToLinearSrgb(l                        ┗━┛
    ┗━━━━┛

[-work/src//oklab.temper.md+954-957]: Cannot translate lab not available from implicits: ❎
kotlin.NotImplementedError: An operation is not implemented: non-function types?
        at lang.temper.be.java.JavaTranslator$ModuleScope.callFunctionValue(JavaTranslator.kt:1384)
...
kotlin.NotImplementedError: An operation is not implemented: GarbageTopLevel
        at lang.temper.be.lua.ModuleParts.translateTopLevel(LuaTranslator.kt:2092)
```

**Comment by tjpalmer** [comment]
And this:

```ts
let hi(): Int { a + 1 }
```

Crashes tmpl translator:

```kt
java.lang.NullPointerException
        at lang.temper.be.tmpl.TranslateCoverFunction.arityInRangeCheck(TranslateCoverFunction.kt:151)
        at lang.temper.be.tmpl.TranslateCoverFunction.translateSignature(TranslateCoverFunction.kt:304)
        at lang.temper.be.tmpl.TranslateCoverFunction.translateSignatures(TranslateCoverFunction.kt:283)
        at lang.temper.be.tmpl.TranslateCoverFunction.translate(TranslateCoverFunction.kt:211)
        at lang.temper.be.tmpl.TranslateCoverFunctionKt.translateCoverFunction(TranslateCoverFunction.kt:34)
        at lang.temper.be.tmpl.TmpLTranslator.translateValueForPool$be(TmpLTranslator.kt:2167)
        at lang.temper.be.tmpl.ConstantPool.fillValue(ConstantPool.kt:129)
...
```

**Comment by tjpalmer** [comment]
More trouble from bad lambda block syntax:

```kt
[-work/src//generic.temper.md+1949-1950]: Cannot translate x not available from implicits: ❎
61: c3 { vec.map { (x); x * 255.0 } }
                        ⇧
[-work/src//generic.temper.md+1953-1954]: Cannot translate x not available from implicits: ❎
kotlin.NotImplementedError: An operation is not implemented.
        at lang.temper.be.csharp.CSharpTranslator.translateExpression(CSharpTranslator.kt:942)
...
java.lang.IllegalStateException: Module function nym`f*#960` not registered
        at lang.temper.be.java.JavaNames.moduleFunction(JavaNames.kt:227)
...
[-work/src/]: Error during translation of colorflap via java backend: java.lang.IllegalStateException: Module function nym`f*#960` not registered
java.lang.IllegalArgumentException: Failed requirement.
        at lang.temper.be.lua.LuaName.<init>(LuaNames.kt:19)
```
