### ISSUE TITLE
Ugly errors and tmpl translator crash on fn type param names

### ISSUE THREAD

**Issue by tjpalmer** [temperlang/temper#80]
I accidentally put a parameter name in the function type here:

```ts
      public map(transform: fn (x: Float64): Float64): Vec3 {
        { x: transform(x), y: transform(y), z: transform(z) }
      }
```

And that causes proper errors like this among other more confusing ones:

```ts
19: map(transform: fn (x: Float64): Float64): Vec3 {
                        ┗━━━━━━━┛
[-work/src//color.temper.md+486-495]@A: Formal argument where actual expected.  `:` only applies to function parameters
```

And then it also breaks tmpl translator and name analysis:

```kt
kotlin.NotImplementedError: An operation is not implemented: TreeWrapper((Decl (L map__64) (V \method) (V \map) (V \visibility) (V \public) (V \ssa) (V void) (V \stay) (S) (V \fromType) (V Vec3))) not understood
        at lang.temper.be.tmpl.TranslateTypeDeclarationKt.translateTypeDeclaration(TranslateTypeDeclaration.kt:385)
...
java.lang.NullPointerException
        at lang.temper.be.names.NameAnalysis.recognizeCallAssign(NameAnalysis.kt:248)
        at lang.temper.be.names.NameAnalysis.access$recognizeCallAssign(NameAnalysis.kt:53)
...
        at lang.temper.be.names.NameAnalysis.<init>(NameAnalysis.kt:109)
        at lang.temper.be.Backend.preanalysis(Backend.kt:141)
```

We should clean up the ugliness. Minimally, after frontend error, we could transform to the same tree expected for proper syntax perhaps.

We've also recently discussed the idea of supporting named parameters in function types.

**Comment by tjpalmer** [comment]
I think @mikesamuel says he has indeed fixed this on his branch.
